/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autochess;

import java.awt.AWTException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Godofga
 */
public class AutoChess extends javax.swing.JFrame {
    Automation obs;
    boolean running = false;
    /**
     * Creates new form GUI
     */
    public AutoChess() {
        initComponents();
        try {
            obs= new Automation();
            Database.resetBoard();
        } catch (AWTException ex) {
            Logger.getLogger(AutoChess.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBot = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonOn = new javax.swing.JButton();
        jLabelSide = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaBoard = new javax.swing.JTextArea();
        jButtonCheckGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonBot.setText("Bot");
        jButtonBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBotActionPerformed(evt);
            }
        });

        jLabel1.setText("Against:");

        jButtonOn.setText("Turn on");
        jButtonOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOnActionPerformed(evt);
            }
        });

        jLabelSide.setText("You're playing with *** pieces!");

        jTextAreaBoard.setEditable(false);
        jTextAreaBoard.setColumns(20);
        jTextAreaBoard.setRows(5);
        jTextAreaBoard.setText("_-_-_-_-_-_-_-_-_\n_-_-_-_-_-_-_-_-_\n_-_-_-_-_-_-_-_-_\n_-_-_-_-_-_-_-_-_\n_-_-_-_-_-_-_-_-_\n_-_-_-_-_-_-_-_-_\n_-_-_-_-_-_-_-_-_\n_-_-_-_-_-_-_-_-_");
        jTextAreaBoard.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextAreaBoard);

        jButtonCheckGame.setText("Check Game");
        jButtonCheckGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButtonOn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSide)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCheckGame)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBot)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonCheckGame)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabelSide))
                        .addComponent(jButtonBot, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBotActionPerformed
        // TODO add your handling code here:
        Database.setCompetitive(!Database.getCompetitive());
        if(Database.competitive)
            jButtonBot.setText("Competitive");
        else
            jButtonBot.setText("Bot");
    }//GEN-LAST:event_jButtonBotActionPerformed

    private void jButtonOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOnActionPerformed
        // TODO add your handling code here:
        if(!running){
                obs.start();
                obs.checkSide();
                jLabelSide.setText(Database.white?"You are playing with white pieces":"You are playing with black pieces");
                
            
        }
        running = true;
    }//GEN-LAST:event_jButtonOnActionPerformed

    private void jButtonCheckGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckGameActionPerformed
        // TODO add your handling code here:
        String board = "";
        for(int i=0;i<8;i++){
            for(int j=0;j<8;j++){
               board+="_" + Database.getBoardCharAt(i,j);
               
            }board+="_\n";
        }
        jTextAreaBoard.setText(board);
        System.out.println(board);
        
    }//GEN-LAST:event_jButtonCheckGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoChess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoChess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoChess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoChess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AutoChess().setVisible(true);
            Uci channel = new Uci();
            channel.start();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBot;
    private javax.swing.JButton jButtonCheckGame;
    private javax.swing.JButton jButtonOn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSide;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaBoard;
    // End of variables declaration//GEN-END:variables
}
